name: Simulated Customer Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- Validator Jobs ---
  validate_pre_release:
    name: Validate Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-Release Validation
        run: |
          echo "Simulate pre-release validation..."
          echo "Done!"

  template_validator:
    name: Template Validator
    runs-on: ubuntu-latest
    needs: [validate_pre_release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Template Validator Step
        run: |
          echo "Simulating template validation..."
          echo "All good!"

  codeowners_validator:
    name: CodeOwners Validator
    runs-on: ubuntu-latest
    needs: [template_validator]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CodeOwners Validation
        run: |
          echo "Simulating CodeOwners check..."
          echo "OK!"

  version_mods_validator:
    name: Version & Mods Validator
    runs-on: ubuntu-latest
    needs: [template_validator]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version & Mods Validation
        run: |
          echo "Simulating version & mods checks..."
          echo "Looks fine!"

  # --- Final Build Job ---
  build:
    name: Build Artifacts
    # This job depends on all validator jobs
    needs: [validate_pre_release, codeowners_validator, version_mods_validator]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact:
          - type: docker
            name: docker-image
            dockerfile: './Dockerfile'
            context: '.'
          - type: jar
            name: service1
            module: 'service1'
          - type: war
            name: war-service1
            module: 'war-service1'
          - type: frontend
            name: frontend-app
            dockerfile: './frontend/Dockerfile'
            context: './frontend'
    env:
      TIMESTAMP: ${{ github.run_id }}   # Using run_id as a pseudo-timestamp

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Artifact
        run: |
          if [ "${{ matrix.artifact.type }}" = "docker" ]; then
            echo "Building Docker image..."
            docker build -t "${{ secrets.JFROG_URL }}/docker/${{ matrix.artifact.name }}:${TIMESTAMP}" \
              -f "${{ matrix.artifact.dockerfile }}" "${{ matrix.artifact.context }}"
            docker push "${{ secrets.JFROG_URL }}/docker/${{ matrix.artifact.name }}:${TIMESTAMP}"
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' \
              "${{ secrets.JFROG_URL }}/docker/${{ matrix.artifact.name }}:${TIMESTAMP}" | cut -d':' -f2)
            echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV

          elif [ "${{ matrix.artifact.type }}" = "jar" ]; then
            echo "Building JAR for module: ${{ matrix.artifact.module }}"
            cd ${{ matrix.artifact.module }}
            mvn clean package -DskipTests
            cd ..
            JAR_FILE=$(ls ${{ matrix.artifact.module }}/target/*.jar | head -n 1)
            echo "Pushing JAR to JFROG Artifactory..."
            curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }}" \
              -T "$JAR_FILE" \
              "${{ secrets.JFROG_URL }}/my-jar-repo/${{ matrix.artifact.module }}/$(basename $JAR_FILE)"

          elif [ "${{ matrix.artifact.type }}" = "war" ]; then
            echo "Building WAR for module: ${{ matrix.artifact.module }}"
            cd ${{ matrix.artifact.module }}
            mvn clean package -DskipTests
            cd ..
            WAR_FILE=$(ls ${{ matrix.artifact.module }}/target/*.war | head -n 1)
            echo "Pushing WAR to JFROG Artifactory..."
            curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }}" \
              -T "$WAR_FILE" \
              "${{ secrets.JFROG_URL }}/my-war-repo/${{ matrix.artifact.module }}/$(basename $WAR_FILE)"

          elif [ "${{ matrix.artifact.type }}" = "frontend" ]; then
            echo "Building Frontend Docker image..."
            docker build -t "${{ secrets.JFROG_URL }}/docker/${{ matrix.artifact.name }}:${TIMESTAMP}" \
              -f "${{ matrix.artifact.dockerfile }}" "${{ matrix.artifact.context }}"
            docker push "${{ secrets.JFROG_URL }}/docker/${{ matrix.artifact.name }}:${TIMESTAMP}"
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' \
              "${{ secrets.JFROG_URL }}/docker/${{ matrix.artifact.name }}:${TIMESTAMP}" | cut -d':' -f2)
            echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV
          
      - name: Send Build Metadata to RabbitMQ
        env:
          RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
        run: |
          if [ "${{ matrix.artifact.type }}" = "docker" ] || [ "${{ matrix.artifact.type }}" = "frontend" ]; then
            PAYLOAD=$(jq -n \
              --arg artifact "${{ matrix.artifact.name }}" \
              --arg tag "$TIMESTAMP" \
              --arg digest "sha256:${{ env.IMAGE_DIGEST }}" \
              '{artifact: $artifact, imageTag: $tag, digest: $digest}')
          elif [ "${{ matrix.artifact.type }}" = "jar" ]; then
            PAYLOAD=$(jq -n --arg artifact "${{ matrix.artifact.name }}" '{artifact: $artifact, type: "jar"}')
          elif [ "${{ matrix.artifact.type }}" = "war" ]; then
            PAYLOAD=$(jq -n --arg artifact "${{ matrix.artifact.name }}" '{artifact: $artifact, type: "war"}')
          fi

          echo "Sending build event to RabbitMQ for artifact: ${{ matrix.artifact.name }}"
          curl -u $RABBITMQ_USER:$RABBITMQ_PASS \
              -H "Content-Type: application/json" \
              -X POST "$RABBITMQ_URL/api/exchanges/%2F/build-events/publish" \
              --data-binary "$(jq -n --arg payload "$PAYLOAD" --arg routing_key "build.event" \
                '{vhost: "/", name: "build-events", routing_key: $routing_key, payload: $payload, payload_encoding: "string"}')"
